FROM nvidia/cuda:11.0.3-devel-ubuntu18.04
WORKDIR /root/workspace
COPY ./pip.conf /root/.pip/pip.conf
COPY ./sources.list /etc/apt/sources.list
RUN apt update && apt install python3 python3-pip
RUN pip install -r /root/requirements.txt
ENV PYTHONBUFFERED 1
