FROM nvidia/cuda:11.0.3-devel-ubuntu18.04

WORKDIR /root/workspace

COPY ./pip.conf /root/.pip/pip.conf
# COPY ./sources.list /etc/apt/sources.list
COPY ./requirements.txt /root/requirements.txt

RUN rm -rf /etc/apt/sources.list.d/* && apt -y update && apt -y install python3 python3-pip && echo alias python=python3 >> ~/.bashrc && echo alias pip=pip3 >> ~/.bashrc \
    apt install -y libsm6 libxext6 libxrender-dev && ln -s /usr/bin/python3.6 /usr/bin/python

RUN pip3 install -r /root/requirements.txt

ENV PYTHONBUFFERED 1
