FROM nvidia/cuda:11.0.3-devel-ubuntu18.04

WORKDIR /root/workspace

COPY ./pip.conf /root/.pip/pip.conf
COPY ./sources.list /etc/apt/sources.list
COPY ./requirements.txt /root/requirements.txt
COPY ./utils ./utils

RUN rm -rf /etc/apt/sources.list.d/* && apt -y update && apt -y install python3 python3-pip && echo alias python=python3 >> ~/.bashrc && echo alias pip=pip3 >> ~/.bashrc
# utils可选，若无需使用，可直接删除
RUN pip3 install -r /root/requirements.txt && cd utils && python3 setup.py sdist && python3 setup.py install

ENV PYTHONBUFFERED 1
