FROM nvidia/cuda:11.0.3-devel-ubuntu18.04

WORKDIR /root/workspace

COPY ./pip.conf /root/.pip/pip.conf
COPY ./sources.list /etc/apt/sources.list
COPY ./requirements.txt /root/requirements.txt

RUN rm -rf /etc/apt/sources.list.d/* && \
    apt -y update && \
    apt-get install build-essential && \
    apt-get install -y apt-utils git curl ca-certificates bzip2 tree htop wget && \
    apt -y install python3.8 python3-pip python3.8-dev && \
    echo alias python=python3 >> ~/.bashrc && echo alias pip=pip3 >> ~/.bashrc \
    apt install -y libglib2.0-0 libsm6 libxext6 libxrender-dev libgl1-mesa-glx bmon iotop g++ && \
    rm -f /usr/bin/python && \
    ln -s /usr/bin/python3.8 /usr/bin/python && \
    rm -f /usr/bin/python3 && \
    ln -s /usr/bin/python3.8 /usr/bin/python3

RUN python -m pip install --upgrade pip && \
    pip3 install --upgrade setuptools

RUN pip install -r /root/requirements.txt

RUN pip3 install SharedArray && \
    pip3 install spconv-cu114

ENV PYTHONBUFFERED 1